# Generated by Django 5.0.7 on 2024-08-03 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='continuarviendo',
            options={'verbose_name': 'Pelicula Usuario', 'verbose_name_plural': 'Peliculas Usuarios'},
        ),
    ]
