# Generated by Django 5.0.7 on 2024-08-04 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_continuarviendo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('id',), 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
    ]
