# Generated by Django 5.0.7 on 2024-08-05 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_category_options'),
        ('users', '0008_alter_perfil_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='continuarviendo',
            name='user',
        ),
        migrations.AddField(
            model_name='continuarviendo',
            name='perfil',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='users.perfil'),
            preserve_default=False,
        ),
    ]
