# Generated by Django 5.0.7 on 2024-08-04 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Nombre Perfil'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='type',
            field=models.CharField(choices=[('0', 'Infantil'), ('1', 'Adultos'), ('2', 'Otro')], default='0', max_length=1, verbose_name='Tipo de Perfil'),
            preserve_default=False,
        ),
    ]
