# Generated by Django 5.0.7 on 2024-08-05 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_perfil_name_alter_perfil_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='pin',
            field=models.CharField(default='', max_length=4, verbose_name='Pin acceso'),
            preserve_default=False,
        ),
    ]
