# Generated by Django 5.0.7 on 2024-08-05 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_perfil_pin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='pin',
            new_name='password',
        ),
        migrations.AddField(
            model_name='perfil',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
