# Generated by Django 5.0.7 on 2024-08-05 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_pin_perfil_password_perfil_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
