# Generated by Django 5.0.7 on 2024-08-05 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_perfil_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='Nombre Perfil'),
        ),
    ]
