# Generated by Django 5.0.7 on 2024-08-06 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_perfil_is_active_perfil_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='password',
        ),
        migrations.AddField(
            model_name='perfil',
            name='pin',
            field=models.CharField(default='', max_length=4, verbose_name='Pin'),
            preserve_default=False,
        ),
    ]
